version: '3'
services:
  tracerapp:
    build: .
    image: tracerapp
    ports:
      - 8080:8080
    depends_on:
      - postgresdb
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/tracer
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  postgresdb:
    build: ./postgres
    image: postgresdb
    environment:
      - POSTGRES_DB=tracer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

  profiledb:
    image: postgresdb
    environment:
      - POSTGRES_DB=profiles
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  profilesapp:
    build: ../../VisualProjects/ProfileAPI/ProfileAPI
    image: pythonapp
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
      - profiledb
